### ISSUE TITLE
OOM when allocating tensor with shape[4,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:FusedBatchNormV3]

### ISSUE THREAD

**Issue by 201810788** [minji-o-j/system-for-visually-impaired#1]
OOM when allocating tensor with shape[4,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:FusedBatchNormV3]

**Comment by 201810788** [comment]
Epoch 0 :
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-56-ad12deb28033> in <module>
----> 1 results = train(EPOCHS, model, train_gen, val_gen, 10, 2, 'training_1')
      2 
      3 plt.plot(results[0])
      4 plt.plot(results[1])

<ipython-input-55-7b09cc17cb6b> in train(epochs, model, train_dataset, val_dataset, steps_per_epoch_train, steps_per_epoch_val, train_name)
     49         for batch_idx in range(steps_per_epoch_train):
     50             img, detector_mask, matching_true_boxes, class_one_hot, true_boxes =  next(train_dataset)
---> 51             loss, _, grads = grad(model, img, detector_mask, matching_true_boxes, class_one_hot, true_boxes)
     52             optimizer.apply_gradients(zip(grads, model.trainable_variables))
     53             epoch_loss.append(loss)

<ipython-input-54-28479602bd97> in grad(model, img, detector_mask, matching_true_boxes, class_one_hot, true_boxes, training)
      2 def grad(model, img, detector_mask, matching_true_boxes, class_one_hot, true_boxes, training=True):
      3     with tf.GradientTape() as tape:
----> 4         y_pred = model(img, training)
      5         loss, sub_loss = yolov2_loss(detector_mask, matching_true_boxes, class_one_hot, true_boxes, y_pred)
      6     return loss, sub_loss, tape.gradient(loss, model.trainable_variables)

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    889           with base_layer_utils.autocast_context_manager(
    890               self._compute_dtype):
--> 891             outputs = self.call(cast_inputs, *args, **kwargs)
    892           self._handle_activity_regularization(inputs, outputs)
    893           self._set_mask_metadata(inputs, outputs, input_masks)

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\engine\network.py in call(self, inputs, training, mask)
    706     return self._run_internal_graph(
    707         inputs, training=training, mask=mask,
--> 708         convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    709 
    710   def compute_output_shape(self, input_shape):

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\engine\network.py in _run_internal_graph(self, inputs, training, mask, convert_kwargs_to_constants)
    858 
    859           # Compute outputs.
--> 860           output_tensors = layer(computed_tensors, **kwargs)
    861 
    862           # Update tensor_dict.

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    889           with base_layer_utils.autocast_context_manager(
    890               self._compute_dtype):
--> 891             outputs = self.call(cast_inputs, *args, **kwargs)
    892           self._handle_activity_regularization(inputs, outputs)
    893           self._set_mask_metadata(inputs, outputs, input_masks)

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\layers\normalization.py in call(self, inputs, training)
    657 
    658     if self.fused:
--> 659       outputs = self._fused_batch_norm(inputs, training=training)
    660       if self.virtual_batch_size is not None:
    661         # Currently never reaches here since fused_batch_norm does not support

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\layers\normalization.py in _fused_batch_norm(self, inputs, training)
    515 
    516     output, mean, variance = tf_utils.smart_cond(
--> 517         training, _fused_batch_norm_training, _fused_batch_norm_inference)
    518     if not self._bessels_correction_test_only:
    519       # Remove Bessel's correction to be consistent with non-fused batch norm.

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py in smart_cond(pred, true_fn, false_fn, name)
     57         pred, true_fn=true_fn, false_fn=false_fn, name=name)
     58   return smart_module.smart_cond(
---> 59       pred, true_fn=true_fn, false_fn=false_fn, name=name)
     60 
     61 

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\framework\smart_cond.py in smart_cond(pred, true_fn, false_fn, name)
     52   if pred_value is not None:
     53     if pred_value:
---> 54       return true_fn()
     55     else:
     56       return false_fn()

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\keras\layers\normalization.py in _fused_batch_norm_training()
    501           beta,
    502           epsilon=self.epsilon,
--> 503           data_format=self._data_format)
    504 
    505     def _fused_batch_norm_inference():

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\ops\nn_impl.py in fused_batch_norm(x, scale, offset, mean, variance, epsilon, data_format, is_training, name)
   1507         data_format=data_format,
   1508         is_training=is_training,
-> 1509         name=name)
   1510     return y, batch_mean, batch_var
   1511 

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py in fused_batch_norm_v3(x, scale, offset, mean, variance, epsilon, data_format, is_training, name)
   4603       else:
   4604         message = e.message
-> 4605       _six.raise_from(_core._status_to_exception(e.code, message), None)
   4606   # Add nodes to the TensorFlow graph.
   4607   if epsilon is None:

c:\users\muho\anaconda3\envs\traffic_light\lib\site-packages\six.py in raise_from(value, from_value)

ResourceExhaustedError: OOM when allocating tensor with shape[4,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:FusedBatchNormV3]

**Comment by minji-o-j** [comment]
batch size 1,2일때만 되고 이보다 클 시 작동 안됨
원래 노트북에 내장된 GPU를 사용했으나
코랩에서 GPU 성능 좋은걸로 하니 해결됨
